name: schedule_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
